files:
  - source: /*.json
    translation: /olga/translations/%locale%.%file_extension%
    languages_mapping:
      locale:
        zh-CN: CH
  - source: /*.po
    translation: /po/trans/%two_letters_code%.%original_file_name%
  - source: /*.ini
    translation: /first/%original_file_name%.%locale_with_underscore%.%language%_final
    languages_mapping:
      language:
        td: Dialect
  - source: /*.properties
    translation: /first_rank/second_rank/third_rank/%three_letters_code%_final
  - source: /*.json
    ignore:
      - /Example_en.json
    translation: /third/%language%
