files:
  - source: '*xliff'
    translation: /GitHub-test/%two_letters_code%/%original_file_name%
  - source: /CLI/*.properties
    translation: /CLI/%two_letters_code%_translated/%original_file_name%
