files:
  - source: /*.json
    translation: /olga/translations/%locale%.%file_extension%
    languages_mapping:
      locale:
        zh-CN: CH
  - source: /*.po
    translation: /po/trans/%two_letters_code%.%original_file_name%
  - source: /*.ini
    translation: /first/%original_file_name%.%locale_with_underscore%.%language%_final.ini
    languages_mapping:
      language:
        td: Dialect
