files:
  - source: /CLI/*.po
    translation: /CLI/%two_letters_code%_translated/%original_file_name%,
         languages_mapping:
        two_letters_code:
          de: den_po
    - source: /CLI/*.properties,
      translation: /CLI/%two_letters_code%_translated/%original_file_name%,
      languages_mapping:
        two_letters_code:
          de: den_prop
